const candidates = [
	'pullrack.com',
	'setrack.com',
	'bindrack.com',
	'holorack.com',
	'deckrack.com',
	'pullledger.com',
	'setledger.com',
	'cardledger.com',
	'hololedger.com',
	'deckledger.com',
	'bindledger.com',
	'pullscout.com',
	'setscout.com',
	'cardscout.com',
	'holoscout.com',
	'deckscout.com',
	'bindscout.com',
	'pullstash.com',
	'setstash.com',
	'cardstash.com',
	'holostash.com',
	'deckstash.com',
	'bindstash.com',
	'bindfolio.com',
	'holofolio.com',
	'deckfolio.com',
	'pullworth.com',
	'setworth.com',
	'deckworth.com',
	'bindworth.com',
	'holoworth.com',
	'slabstash.com',
	'slabscout.com',
	'packstash.com',
	'packscout.com',
	'packledger.com',
	'foilstash.com',
	'foilscout.com',
	'holopull.com',
	'deckpull.com',
	'setpull.com',
	'bindpull.com',
	'pullbind.com',
	'setbind.com',
	'deckbind.com',
	'bindbase.com',
	'pullbase.com',
	'setbase.com',
	'holobase.com',
	'deckbase.com',
	'tcgledger.com',
	'tcgscout.com',
	'tcgstash.com',
	'tcgpulse.com',
	'pullbox.com',
	'setbox.com',
	'holobox.com',
	'cardcrate.com',
	'deckcrate.com',
	'pullcrate.com',
	'setcrate.com',
	'bindcrate.com',
	'bindly.com',
	'pullly.com',
	'setly.com',
	'hololy.com',
	'deckly.com',
	'bindlist.com',
	'hololist.com',
	'setlisthq.com',
	'pullchart.com',
	'setchart.com',
	'cardchart.com',
	'holochart.com',
	'pricebinder.com',
	'bindprice.com',
	'setpricehq.com',
	'pullprice.com',
	'fullbinder.com',
	'everyset.com',
	'setcomplete.com',
	'cardcomplete.com',
	'playsethq.com',
	'completionhq.com',
	'rarityrack.com',
	'raritystash.com',
	'packworth.com',
	'slabworth.com',
	'foilworth.com',
	'holoindex.com',
	'setindexer.com',
	'cardindexer.com',
	'pullindexer.com',
	'bindindex.com',
	'setmapper.com',
	'cardmapper.com',
	'pullmapper.com',
	'deckmapper.com',
	'holomapper.com',
	'bindmapper.com',
	'slabmapper.com',
	'packmapper.com',
	'foilmapper.com',
	'raritymap.com',
	'setwatch.com',
	'pullwatch.com',
	'holoatlas.com',
	'deckatlas.com',
	'bindatlas.com',
	'setatlas.com',
	'pullatlas.com',
	'getsetly.com',
	'usepullr.com',
	'openbindr.com',
	'trysetly.com',
	'mysetstash.com',
	'thesetstash.com',
	'gotpull.com',
	'gotsets.com',
	'gotbind.com',
	'gotfoil.com',
	'gotholo.com',
	'ripstash.com',
	'ripscout.com',
	'rippull.com',
	'ripsets.com',
	'packrip.com',
	'slabrip.com',
	'bindrip.com',
	'setrip.com',
	'cardrip.com',
	'deckrip.com',
	'holodex.com',
	'setdex.com',
	'pulldex.com',
	'binddex.com',
	'deckdex.com',
	'carddex.com',
	'slabdex.com',
	'packdex.com',
	'foildex.com',
	'raritydex.com',
	'setchecklist.com',
	'pullchecklist.com',
	'deckchecklist.com',
	'holochecklist.com',
	'bindchecklist.com',
	'slabcheck.com',
	'packchecklist.com',
	'foillist.com',
	'slablist.com',
	'packlisttcg.com',
	'bindertcg.com',
	'pullertcg.com',
	'setertcg.com',
	'holertcg.com',
	'deckertcg.com',
	'cardertcg.com',
	'slabertcg.com',
	'packertcg.com',
	'foilertcg.com',
	'rarityertcg.com',
	'checklistertcg.com',
	'vaultpull.com',
	'vaultset.com',
	'vaultbind.com',
	'vaultdeck.com',
	'vaultfoil.com',
	'vaultslab.com',
	'vaultpack.com',
	'vaultrip.com',
	'vaultdex.com',
	'vaultchart.com',
	'vaultscout.com',
	'vaultstash.com',
	'vaultledger.com',
	'vaultatlas.com',
	'vaultmapper.com',
	'vaultindex.com',
	'vaultchecklist.com',
	'vaultcomplete.com',
	'vaultwatch.com',
	'vaultprice.com',
	'vaultworth.com',
	'vaultfolio.com',
	'vaultbase.com',
	'vaultbox.com',
	'vaultcrate.com',
	'vaultly.com',
	'vaultlist.com',
	'vaultrack.com',
	'vaultrip.com',
	'pulldex.io',
	'setdex.io',
	'holodex.io',
	'binddex.io',
	'deckdex.io',
	'carddex.io',
	'slabdex.io',
	'packdex.io',
	'foildex.io',
	'raritydex.io',
	'pulldex.app',
	'setdex.app',
	'holodex.app',
	'binddex.app',
	'deckdex.app',
	'carddex.app',
	'slabdex.app',
	'packdex.app',
	'foildex.app',
	'raritydex.app',
	'pulldex.dev',
	'setdex.dev',
	'holodex.dev',
	'binddex.dev',
	'deckdex.dev',
	'carddex.dev',
	'slabdex.dev',
	'packdex.dev',
	'foildex.dev',
	'raritydex.dev',
	'pulldex.cards',
	'setdex.cards',
	'holodex.cards',
	'binddex.cards',
	'deckdex.cards',
	'carddex.cards',
	'slabdex.cards',
	'packdex.cards',
	'foildex.cards',
	'raritydex.cards'
];

async function checkCom(domain: string): Promise<boolean> {
	const res = await fetch(`https://rdap.verisign.com/com/v1/domain/${domain}`, {
		headers: { Accept: 'application/rdap+json' }
	});
	if (res.status === 404) return true;
	if (res.status === 200) return false;
	throw new Error(`${domain}: unexpected RDAP status ${res.status}`);
}

async function checkOther(domain: string): Promise<boolean> {
	const res = await fetch(`https://rdap.org/domain/${domain}`, {
		headers: { Accept: 'application/rdap+json' },
		redirect: 'follow'
	});
	if (res.status === 404) return true;
	if (res.status === 200) {
		const body = (await res.json()) as { errorCode?: number };
		if (body.errorCode === 404) return true;
		return false;
	}
	throw new Error(`${domain}: unexpected RDAP status ${res.status}`);
}

async function isAvailable(domain: string): Promise<boolean> {
	return domain.endsWith('.com') ? checkCom(domain) : checkOther(domain);
}

const available: string[] = [];
const errors: string[] = [];

for (const domain of candidates) {
	try {
		if (await isAvailable(domain)) available.push(domain);
		await new Promise((r) => setTimeout(r, 120));
	} catch (err) {
		errors.push(`${domain}: ${err instanceof Error ? err.message : String(err)}`);
	}
}

available.sort();
console.log(JSON.stringify({ available, errors }, null, 2));
console.error(`Checked ${candidates.length}, available ${available.length}, errors ${errors.length}`);
